refactor : about
COPS-IITBHU/cops-site pull request #43
Opened 2021-05-22 15:06 UTC by aswinidev

Refactored About

- Removed Vuetify Components
- Added TailwindCSS

2021-05-22 18:17 UTC, m-e-l-u-h-a-n commented
@aswinidev can you post a screenshot for this changed card. You can use it in any page for screenshot.

2021-05-28 03:09 UTC, aswinidev commented
![Screenshot from 2021-05-28 08-38-52](https://user-images.githubusercontent.com/76481696/119923862-2dd40e80-bf90-11eb-8c76-2599a221554e.png)

2021-05-28 15:46 UTC, m-e-l-u-h-a-n commented on components/About.vue
> +      <hr class="tw-my-3" />
I think this can be removed. As card already has its own shadow.

2021-05-28 15:49 UTC, m-e-l-u-h-a-n requested changes
I went through the changes and posted a minor comment. There are also linting error. that need to be addressed.
Rest looks fine 🎉.

2021-05-29 20:40 UTC, aswinidev commented
I made the requested changes and also fixed the linting error

2021-05-30 03:22 UTC, m-e-l-u-h-a-n approved these changes

2021-05-30 03:22 UTC, merged

2021-05-30 03:23 UTC, m-e-l-u-h-a-n commented
LGTM, Merged🎊!
Thanks for working on it.