Removed vuetify components from index.vue
COPS-IITBHU/cops-site pull request #45
Opened 2021-06-04 16:42 UTC by shukapurv

### In ./pages/index.vue
### Removed vuetify components and used tailwind classes and HTML tags instead
![Screenshot 2021-06-04 at 10 03 42 PM](https://user-images.githubusercontent.com/73848723/120834985-62902900-c581-11eb-8e6b-942f3965f944.png)

2021-06-05 04:30 UTC, KKVANONYMOUS commented
@shukapurv There are some conflicts in your PR. I guess these conflicts are due to your fork being not even with the main branch. So, update your fork accordingly and then create a new PR with the proposed changes.

2021-06-07 10:08 UTC, shukapurv commented
@KKVANONYMOUS I tried to resolve the conflicts, I guess now there is no conflict in my PR.
Should i create new PR or is it okay?

2021-06-08 11:35 UTC, KKVANONYMOUS requested changes
One more thing, instead of using `div` everywhere you can make use of semantic HTML to increase the readability of the code

2021-06-08 11:35 UTC, KKVANONYMOUS commented on pages/index.vue
> +        </div>
No need of social media links here. Already added into footer

2021-06-08 11:35 UTC, KKVANONYMOUS commented on pages/index.vue
> +  },
No need of this also

2021-06-08 11:35 UTC, KKVANONYMOUS commented on pages/index.vue
> +      ],
This can be removed as icons are already there in footer

2021-08-15 09:27 UTC, closed without merging